### ISSUE TITLE
SHACL Path Expression Not Matching Expected SPARQL Property Path

### ISSUE THREAD

**Issue by ch-sander** [sparna-git/Sparnatural#711]
A bug related to #688 :

`sh:path ( [ sh:alternativePath ( [ sh:zeroOrMorePath grace:object_object ] [ sh:zeroOrMorePath grace:event_object ] ) ] grace:type_object grace:called ) .`

this should lead to:

`((grace:object_object*)|(grace:event_object*))/grace:type_object/grace:called`

but it leads to:

`((grace:object_object*)|((grace:event_object*)/grace:type_object/grace:called))`

can you reproduce this @tfrancart ?

**Comment by ch-sander** [comment]
`sh:path ( [ sh:zeroOrMorePath [ sh:alternativePath ( grace:object_object grace:event_object ) ] ] grace:type_object grace:called )`

leads to

`(grace:object_object|((grace:event_object*)/grace:type_object/grace:called))`

but should (I think):

`(grace:object_object|grace:event_object)*/grace:type_object/grace:called`

**Comment by tfrancart** [comment]
Right now I don't see how this is possible with the property path conversion code and I suspect this is due to how sparqljs parses and then reserializes the query.
The property path conversion algorithm in Sparnatural is here : https://github.com/sparna-git/Sparnatural/blob/4c0aceabecb2a0ba1a367bde352c911228a01d9c/src/sparnatural/spec-providers/shacl/SHACLSpecificationProvider.ts#L476.

**Comment by ch-sander** [comment]
> Right now I don't see how this is possible with the property path conversion code and I suspect this is due to how sparqljs parses and then reserializes the query.

You mean a fix is out of scope or you mean my result is impossible in the sense of not reproducible by yourself?

Anyway, I see this is a nerdy problem — but meaningful to our project.

**Comment by ch-sander** [comment]
> How can I reproduce ?

You can try my config/endpoint
https://dataria.org/static/sparnatural/config.ttl for https://dataria.org/ask

```ttl
g17sn:property_1422 a sh:PropertyShape ;
    rdfs:label "feature labels"@en ;
    volipi:message "Returns list of all type labels (ideal for concatenation) (This is only a query pattern)" ;
    dash:searchWidget sparnatural:AutocompleteProperty ;
    sh:class g17sn:name ;
    sh:description "Returns list of all type labels (ideal for concatenation)" ;
    sh:name "feature labels" ;
    sh:node g17sn:name_1156 ;
    sh:nodeKind sh:IRI ;
    sh:path ( [ sh:zeroOrMorePath [ sh:alternativePath ( grace:object_object grace:event_object ) ] ] grace:type_object grace:called ) .
```

> 
> Can you confirm you use the latest version ? 

yes, double-checked

> do you have the ability to add a `console.log` debug in the pathToSparql query to double-check its output ?

I have no knowledge of ts/js, not compiling the js and maps myself, editing the compiled files seems difficult. If you recompile with a debug log in https://github.com/sparna-git/Sparnatural/blob/4c0aceabecb2a0ba1a367bde352c911228a01d9c/src/sparnatural/spec-providers/shacl/SHACLSpecificationProvider.ts#L476 I'm more than happy to investigate!

**Comment by ch-sander** [comment]
Or maybe allow to set a hard-coded SPARQL path directly (like `sparqlString` for the OWL-based config)? I think the custom property paths are one of the strongest features of Sparnatural as they allow to navigate a complex graph with ease for users not knowing the ontology.

**Comment by tfrancart** [comment]
I cannot find the first path you gave `( [ sh:alternativePath ( [ sh:zeroOrMorePath grace:object_object ] [ sh:zeroOrMorePath grace:event_object ] ) ] grace:type_object grace:called )` in https://dataria.org/static/sparnatural/config.ttl, where is it ?

Regarding `( [ sh:zeroOrMorePath [ sh:alternativePath ( grace:object_object grace:event_object ) ] ] grace:type_object grace:called )`, it is on g17sn:property_1422 and it is indeed returning the expected path:

![Image](https://github.com/user-attachments/assets/42f1f608-b3ee-4366-943e-cc0b25d7d62e)

This was fixed in #688 but this is not included in a release yet.

Setting sparqlString is not an option, we need to have a working shacl-to-sparql conversion, so I am happy to help sorting tis out.

**Comment by ch-sander** [comment]
> I cannot find the first path you gave `( [ sh:alternativePath ( [ sh:zeroOrMorePath grace:object_object ] [ sh:zeroOrMorePath grace:event_object ] ) ] grace:type_object grace:called )` in https://dataria.org/static/sparnatural/config.ttl, where is it ?

It was a temporary test for the same property. I can add this separately for testing.



> Regarding `( [ sh:zeroOrMorePath [ sh:alternativePath ( grace:object_object grace:event_object ) ] ] grace:type_object grace:called )`, it is on g17sn:property_1422 and it is indeed returning the expected path:
> 
> ![Image](https://github.com/user-attachments/assets/42f1f608-b3ee-4366-943e-cc0b25d7d62e)
> 
> This was fixed in #688 but this is not included in a release yet.

Ah, I was confused actually because I thought it was in `latest`. Can you share a `dev` release for me to test?
> 
> Setting sparqlString is not an option, we need to have a working shacl-to-sparql conversion, so I am happy to help sorting tis out.
> 

I understand and am very grateful for your support

**Comment by tfrancart** [comment]
@ch-sander a 10.2.0 was just released : https://github.com/sparna-git/Sparnatural/releases/tag/10.2.0
Can you test and let me know ? thanks

**Comment by ch-sander** [comment]
My first test appears that 10.2.0 fixed #711. I will reopen if an issue remains. Thanks for the swift and efficient trouble shooting!
